

labels = ['Chili  Healthy', 'Chili  Leaf Curl', 'Chili  Leaf Spot', 'Chili  Whitefly', 'Chili  Yellowish', 'Corn  Common Rust', 'Corn  Gray Leaf Spot', 'Corn  Healthy', 'Corn  Northern Leaf Blight', 'Mango  Diseased', 'Mango  Healthy', 'Pepper Bell  Bacterial Spot', 'Pepper Bell  Healthy', 'Potato  Early Blight', 'Potato  Healthy', 'Potato  Late Blight',
          'Rice  Brown Spot', 'Rice  Healthy', 'Rice  Hispa', 'Rice  Leaf Blast', 'Rice  Neck Blast', 'Tomato  Bacterial Spot', 'Tomato  Early Blight', 'Tomato  Healthy', 'Tomato  Late Blight', 'Tomato  Leaf Mold', 'Tomato  Mosaic Virus', 'Tomato  Septoria Leaf Spot', 'Tomato  Spider Mites (Two Spotted Spider Mite)', 'Tomato  Target Spot', 'Tomato  Yellow Leaf Curl Virus']

causes = {'Chili  Leaf Curl': '**Causes of Chili Leaf Curl**\n'
          '\n'
          '1. **Virus Infection:** Primarily caused by the Chili '
          'leaf curl virus (ChLCV), a begomovirus transmitted by '
          'whiteflies.\n'
          '\n'
          '2. **Vector Transmission:** Whiteflies (primarily '
          'Bemisia tabaci) acquire the virus from infected plants '
          'and transmit it to healthy plants through feeding.\n'
          '\n'
          '3. **Genetic Variation:** Different strains of ChLCV '
          'exist, with varying levels of virulence and '
          'transmissibility.\n'
          '\n'
          '4. **Environmental Factors:** Warm, dry weather and high '
          'whitefly populations favor disease spread.\n'
          '\n'
          '5. **Host Susceptibility:** Some chili varieties are '
          'more susceptible to leaf curl infection than others due '
          'to genetic factors and defense mechanisms.',
          'Chili  Leaf Spot': '1. **Bacterial Infection**: Caused by the bacterium '
          '_Xanthomonas axonopodis_ pv. _vesicatoria_, which enters '
          'through natural openings or wounds in the plant tissue.\n'
          '\n'
          '2. **Fungal Infection**: _Cercospora capsici_ fungus '
          'primarily infects the leaves, causing circular to '
          'irregular spots with chlorotic halos.\n'
          '\n'
          '3. **Botrytis Blight**: Caused by the fungus _Botrytis '
          'cinerea_, this disease affects leaves, stems, and '
          'fruits, leading to soft rots and brown spots.\n'
          '\n'
          '4. **Alternaria Leaf Spot**: _Alternaria solani_ fungus '
          'causes angular or circular spots with concentric rings, '
          'often with a black center.\n'
          '\n'
          '5. **Virus-Induced Leaf Spot**: Caused by viruses such '
          'as the Tobacco mosaic virus (TMV), which leads to mosaic '
          'patterns and distorted leaves.',
          'Chili  Whitefly': '**Causes of Chili Whitefly:**\n'
          '\n'
          '1. **Virus Transmission:** The whitefly (Bemisia tabaci) '
          'is a vector for various viruses that infect chili plants, '
          'including the Chilli leaf curl virus and the Tomato '
          'yellow leaf curl virus. These viruses are transmitted '
          "through the plant's phloem during whitefly feeding.\n"
          "2. **Direct Feeding:** Whiteflies pierce the plant's "
          'tissues with their piercing-sucking mouthparts and feed '
          'on the sap. This feeding deprives the plant of nutrients '
          'and can weaken its growth and development.\n'
          '3. **Honeydew Production:** Whiteflies excrete a sugary '
          'substance called honeydew, which can cover the leaves and '
          'provide a breeding ground for sooty mold fungi. Sooty '
          'mold blocks sunlight from reaching the leaves, further '
          'inhibiting plant growth.\n'
          '4. **Overcrowding:** High populations of whiteflies can '
          'lead to overcrowding, which increases competition for '
          'resources and can weaken the plant. Overcrowding can also '
          'facilitate the spread of viruses and other pathogens.\n'
          '5. **Environmental Conditions:** Warm temperatures and '
          'high humidity favor the growth and reproduction of '
          'whiteflies. Warm, dry conditions can also stress the '
          'chili plant, making it more susceptible to whitefly '
          'damage.',
          'Chili  Yellowish': '**Causes of Chili Yellowish**\n'
          '\n'
          '1. **Nutrient Deficiency:** Yellowing can indicate '
          'deficiencies in essential nutrients like nitrogen, '
          'potassium, or magnesium.\n'
          '2. **Soil Compaction:** Poor soil drainage and '
          'compaction can limit root development and nutrient '
          'uptake, leading to yellowing.\n'
          '3. **Fusarium Wilt:** A soil-borne fungus that infects '
          'the roots and vascular system, causing wilting and '
          'yellowing.\n'
          '4. **Verticillium Wilt:** Another soil-borne fungus that '
          'infects the xylem vessels, restricting water and '
          'nutrient transport, resulting in yellowing.\n'
          '5. **Bacterial Wilt:** Transmitted by contaminated seed '
          'or soil, this bacterial disease causes yellowing, '
          'wilting, and plant collapse.',
          'Corn  Common Rust': '**Causes of Corn Common Rust:**\n'
          '\n'
          '1. **Fungal Pathogen:** Caused by the fungus *Puccinia '
          'sorghi*, which infects corn plants through stomata.\n'
          '2. **Favorable Conditions:** Optimal conditions for '
          'infection include warm, humid weather with ample '
          'moisture and temperatures between 18-24°C (64-75°F).\n'
          '3. **Spore Dispersal:** Wind, insects, or human '
          'activity can spread spores of the fungus to healthy '
          'corn plants.\n'
          '4. **Host Resistance:** Some corn varieties exhibit '
          'varying levels of resistance to common rust, but none '
          'are immune.\n'
          '5. **Crop Management Practices:** Poor crop rotation, '
          'excessive nitrogen fertilization, and dense planting '
          'can increase the risk of common rust infection by '
          'creating an environment conducive to fungal growth.',
          'Corn  Gray Leaf Spot': '**Causes of Corn Gray Leaf Spot**\n'
          '\n'
          '1. **Fungal Pathogen:** Caused by the fungus '
          '*Cercospora zeae-maydis*.\n'
          '2. **Warm, Humid Conditions:** Favorable conditions '
          'for fungal growth and spread.\n'
          '3. **Moisture on Leaves:** Water droplets provide an '
          'ideal environment for spore germination and '
          'infection.\n'
          '4. **Plant Stress:** Weakened plants (e.g., drought, '
          'nutrient deficiencies) are more susceptible to '
          'infection.\n'
          '5. **Crop Residue:** Infected crop residue provides '
          'a source of inoculum for the fungus to overwinter '
          'and spread in the following season.',
          'Corn  Northern Leaf Blight': '1. **Fungal Pathogen**: Caused by the fungus '
          '*Exserohilum turcicum*.\n'
                               '2. **Spore Dispersal**: Spores are dispersed '
                               'by wind and water, infecting leaves through '
                               'natural openings or wounds.\n'
                               '3. **Cool, Wet Conditions**: Ideal for fungal '
                               'growth and infection; occurs during periods of '
                               'high humidity and moderate temperatures.\n'
                               '4. **Previous Crop Residue**: Infected crop '
                               'residue from previous seasons provides a '
                               'source of inoculum for new infections.\n'
                               '5. **Susceptible Varieties**: Certain corn '
                               'varieties are more susceptible to Northern '
                               'Leaf Blight, particularly those with thinner, '
                               'more upright leaves.',
          'Mango  Diseased': '**Causes of Mango Diseases:**\n'
          '\n'
          '1. **Anthracnose (caused by Colletotrichum '
          'gloeosporioides):** Fungal infection causing sunken, '
          'circular lesions on fruits, leaves, and stems.\n'
          '2. **Powdery Mildew (caused by Oidium mangiferae):** '
          'Fungal infection forming a white, powdery growth on '
          'leaves, stems, and fruits, reducing photosynthesis.\n'
          '3. **Bacterial Canker (caused by Xanthomonas axonopodis '
          'pv. mangiferaeindicae):** Bacterial infection resulting '
          'in raised, water-soaked lesions on leaves and fruits, '
          'eventually leading to wilting and defoliation.\n'
          '4. **Stem End Rot (caused by Botryosphaeria spp.):** '
          'Fungal infection affecting mature or ripening fruits, '
          'causing a dark brown rot at the stem end, leading to '
          'fruit drop.\n'
          '5. **Malformation (caused by Fusarium spp.):** Fungal '
          'infection causing severe distortion of leaves, flowers, '
          'and fruits, reducing yield and fruit quality.',
          'Pepper Bell  Bacterial Spot': 'Causes of Pepper Bacterial Spot:\n'
          '\n'
          '1. **Pathogen:** Caused by the bacterium '
          'Xanthomonas euvesicatoria.\n'
          '\n'
          '2. **Entry:** Bacteria enter through wounds '
          'or natural openings (e.g., stomata) on leaves '
          'and stems.\n'
          '\n'
          '3. **Favorable Conditions:** Spreads rapidly '
          'in warm, humid environments with frequent '
          'rainfall or irrigation.\n'
          '\n'
          '4. **Dissemination:** Bacteria can be spread '
          'by water, wind, insects, tools, or '
          'contaminated equipment.\n'
          '\n'
          '5. **Host Range:** Primarily affects bell '
          'peppers, but also sweet and hot peppers, '
          'eggplant, and tomato.',
          'Potato  Early Blight': '**Causes of Potato Early Blight**\n'
          '\n'
          '1. **Fungal Pathogen:** Caused by the fungus '
          '*Alternaria solani*, which thrives in warm, humid '
          'environments.\n'
          '2. **Favorable Conditions:** Warm temperatures '
          '(20-30°C), high humidity (>90%), and extended '
          'periods of leaf wetness promote disease '
          'development.\n'
          '3. **Survival and Inoculum:** The fungus survives in '
          'crop debris, infected tubers, and volunteer plants. '
          'Spores are dispersed by wind and rain.\n'
          '4. **Infection Entry:** Spores germinate on leaf '
          'surfaces and penetrate through natural openings, '
          'wounds, or stomata.\n'
          '5. **Host Susceptibility:** Some potato cultivars '
          'are more susceptible to early blight than others due '
          'to differences in leaf morphology, waxiness, and '
          'trichome density.',
          'Potato  Late Blight': '1. **Pathogen:** Phytophthora infestans, a water '
          'mold-like fungus\n'
          '2. **Environmental conditions:** Cool, humid weather '
          'with heavy rainfall or dew\n'
          '3. **Initial infection:** Spores germinate on plant '
          'surfaces, requiring free water for a few hours\n'
          '4. **Spread:** Spores are dispersed by wind or water '
          'and can rapidly infect new plants\n'
          '5. **Favorable host:** Potato plants are highly '
          'susceptible, especially those with thick foliage and '
          'high nitrogen content',
          'Rice  Brown Spot': '**Causes of Rice Brown Spot:**\n'
          '\n'
          '* **Fungus:** The disease is caused by the fungus '
          '_Magnaporthe oryzae_ (anamorph: _Pyricularia oryzae_), '
          'which infects rice leaves, panicles, and grains.\n'
          '* **Environmental conditions:** Warm and humid '
          'conditions (25-30°C, relative humidity >90%) favor '
          'disease development and spread.\n'
          '* **Moisture accumulation:** Excessive leaf wetness (due '
          'to dew, rain, or irrigation) allows the fungus to '
          'germinate and penetrate the plant.\n'
          '* **Wind and rain:** Wind and rainfall can disperse the '
          'spores of the fungus over long distances, leading to new '
          'infections.\n'
          '* **High nitrogen fertilization:** Excessive nitrogen '
          'fertilization can promote dense canopy growth, creating '
          'a favorable microclimate for disease development.',
          'Rice  Hispa': '**Causes of Rice Hispa**\n'
          '\n'
          '1. **Infestation by hispa beetle (Hispa armigera):** Adults '
          'and larvae of this beetle feed on rice leaves, creating '
          'characteristic hispa blisters.\n'
          '\n'
          '2. **Favorable environmental conditions:** Warm and humid '
          'conditions during the rice growing season promote hispa '
          'beetle activity and egg-laying.\n'
          '\n'
          '3. **High nitrogen fertilization:** Excessive nitrogen '
          'application can stimulate lush foliage growth, making the '
          'rice plants more susceptible to hispa damage.\n'
          '\n'
          '4. **Improper pest management:** Lack of timely control '
          'measures, such as insecticide application or biological '
          'control agents, can lead to severe hispa infestations.\n'
          '\n'
          '5. **Presence of alternative host plants:** Hispa beetles can '
          'also infest other plants in the vicinity of rice fields, such '
          'as grasses and weeds, which serve as reservoirs for the '
          'beetles.',
          'Rice  Leaf Blast': '1. **Magnaporthe oryzae:** The primary causal agent, a '
          'fungus that attacks the leaves of rice plants, causing '
          'lesions that can lead to severe yield loss.\n'
          '\n'
          '2. **Environmental Conditions:** Favorable conditions '
          'for the pathogen include high humidity, warm '
          'temperatures, and prolonged leaf wetness.\n'
          '\n'
          '3. **Plant Susceptibility:** Susceptible rice varieties '
          'and their specific growth stages, particularly the '
          'tillering and booting stages, are more vulnerable to '
          'infection.\n'
          '\n'
          '4. **Cultural Practices:** Improper nitrogen management, '
          'dense planting, and poor field drainage can create an '
          'environment conducive to leaf blast development.\n'
          '\n'
          '5. **Spore Dissemination:** The release and dispersal of '
          'spores from infected plant material, through wind, rain, '
          'and irrigation water, contribute to the spread of the '
          'disease.',
          'Rice  Neck Blast': '- **Magnaporthe oryzae (anamorph: Pyricularia oryzae)**: '
          'The fungus responsible for rice neck blast.\n'
          '\n'
          '- **Environmental conditions**: Warm and humid '
          'conditions, particularly during flowering, favor disease '
          'development.\n'
          '\n'
          '- **Crop management practices**: Excess nitrogen '
          'fertilization, dense planting, and poor drainage can '
          'increase disease severity.\n'
          '\n'
          '- **Resistant cultivars**: Susceptible cultivars are '
          'more likely to develop neck blast.\n'
          '\n'
          '- **Sporulation and spread**: Spores from infected '
          'plants are dispersed by wind and water, spreading the '
          'disease to new areas.',
          'Tomato  Bacterial Spot': '**Causes of Tomato Bacterial Spot:**\n'
          '\n'
          '1. **Bacteria:** The disease is caused by the '
          'bacterium *Xanthomonas perforans*, which infects '
          'through leaf wounds or natural openings.\n'
          '2. **Environmental Conditions:** Warm temperatures '
          '(27-32°C) and high humidity favor disease '
          'development and spread.\n'
          '3. **Contaminated Seeds:** The bacteria can be '
          'carried on infected seeds, perpetuating the '
          'disease from season to season.\n'
          '4. **Insect Transmission:** Insects, such as flea '
          'beetles and thrips, can transmit the bacteria from '
          'infected to healthy plants.\n'
          '5. **Cultural Practices:** Poor sanitation, '
          'overcrowding, and excessive nitrogen fertilization '
          'can create favorable conditions for bacterial '
          'growth and spread.',
          'Tomato  Early Blight': '**Causes of Tomato Early Blight:**\n'
                         '\n'
                         '1. **Fungal Pathogen:** Caused by the fungus '
                         '*Alternaria solani*, which survives in crop residues '
                         'or as spores on weeds.\n'
                         '2. **Favorable Conditions:** Warm and humid weather '
                         '(21-27°C) with frequent rainfall or irrigation '
                         'provides ideal conditions for fungal growth.\n'
                         '3. **Leaf Wetness:** Extended periods of leaf '
                         'wetness, due to dew, rain, or sprinkler irrigation, '
                         'facilitate spore germination and infection.\n'
                         '4. **Injured Plant Tissue:** Wounds on leaves or '
                         'stems created by insects, machinery, or hail can '
                         'provide entry points for the fungus.\n'
                         '5. **Nutritional Deficiency:** Low calcium levels in '
                         'plants can make them more susceptible to early '
                         'blight infection.',
          'Tomato  Late Blight': '1. **Pathogen:** Causative agent is the fungus-like '
          'oomycete _Phytophthora infestans_.\n'
          '2. **Environmental Conditions:** Favorable conditions '
          'for disease development include prolonged periods of '
          'high humidity, cool temperatures, and ample moisture '
          'availability.\n'
          '3. **Infection Pathways:** Spores are dispersed by '
          'wind and rain and can enter the plant through natural '
          'openings (stomata) or wounds.\n'
          '4. **Host Susceptibility:** Some tomato cultivars are '
          'more susceptible to late blight than others. '
          'Environmental stress can also increase '
          'susceptibility.\n'
          '5. **Management Challenges:** Late blight can spread '
          'rapidly, making control difficult. Continuous '
          'cropping, extended periods of wetness, and nearby '
          'infected plants contribute to disease persistence.',
          'Tomato  Leaf Mold': '**Causes of Tomato Leaf Mold**\n'
          '\n'
          '1. **Fungus:** Caused by the oomycete fungus '
          '_Cladosporium fulvum_.\n'
          '2. **Cool, Humid Conditions:** Wet weather, high '
          'humidity, and temperatures between 59-77°F (15-25°C) '
          'favor disease development.\n'
          '3. **Spore Dispersal:** Fungal spores spread through '
          'splashing water, wind, infected plant debris, or '
          'contaminated tools.\n'
          '4. **Intrinsic Factors:** Susceptible tomato cultivars '
          'with thin leaves, fewer trichomes, and lower levels of '
          'antifungal compounds are more prone to infection.\n'
          '5. **Environmental Stress:** Drought, heat stress, or '
          'nutrient deficiencies can weaken tomato plants and make '
          'them more susceptible to infection.',
          'Tomato  Mosaic Virus': '**1. Viral Infection:** Tomato Mosaic Virus (ToMV) '
                         'is caused by the Tomato mosaic virus, a '
                         'single-stranded RNA virus belonging to the family '
                         'Tobamovirus.\n'
                         '\n'
                         '**2. Transmission by Aphids:** The virus is '
                         'primarily transmitted by aphids, which feed on '
                         'infected plants and then spread the virus to healthy '
                         'plants through their piercings and feeding.\n'
                         '\n'
                         '**3. Contact Transmission:** ToMV can also be '
                         'transmitted through contact with infected plant '
                         'material, such as tools, clothing, or hands, that '
                         'have come into contact with the virus.\n'
                         '\n'
                         '**4. Seed Transmission:** In rare cases, ToMV can be '
                         'transmitted through infected seeds, although this is '
                         'less common.\n'
                         '\n'
                         '**5. Environmental Conditions:** Optimal conditions '
                         'for ToMV infection include mild temperatures '
                         '(59-86°F) and high humidity, which favor both virus '
                         'replication and aphid activity.',
          'Tomato  Septoria Leaf Spot': '**Causes of Tomato Septoria Leaf Spot:**\n'
                               '\n'
                               '1. **Fungal Pathogen:** The disease is caused '
                               'by the fungus *Septoria lycopersici* which '
                               'survives on infected crop debris.\n'
                               '2. **Spore Dispersal:** Fungal spores are '
                               'spread by wind, rain, and irrigation water, '
                               'facilitating infection.\n'
                               '3. **Favourable Environment:** Cool, humid '
                               'conditions with temperatures between 55-75°F '
                               '(13-24°C) and high humidity favour disease '
                               'development.\n'
                               '4. **Leaf Wetness:** Wet leaf surfaces for '
                               'extended periods allow fungal spores to '
                               'germinate and establish infections.\n'
                               '5. **Host Susceptibility:** Certain tomato '
                               'varieties are more susceptible to Septoria '
                               'Leaf Spot, particularly those with thin leaves '
                               'and dense canopies.',
          'Tomato  Spider Mites (Two Spotted Spider Mite)': '1. **Overly Dry '
          'Conditions:** Spider mites '
          'thrive in hot, dry '
          'environments, so drought '
          'stress and lack of water '
          'can promote their '
          'proliferation.\n'
          '\n'
          '2. **Abundance of Host '
          'Plants:** When tomatoes '
          'are densely planted or in '
          'close proximity to other '
          'host plants (e.g., '
          'eggplants, peppers), they '
          'provide an ample food '
          'source for spider mites.\n'
          '\n'
          '3. **Presence of Weeds:** '
          'Weeds can harbor spider '
          'mites and provide a bridge '
          'for their spread to tomato '
          'plants.\n'
          '\n'
          '4. **Reduced Predators:** '
          'Beneficial insects like '
          'ladybugs and predatory '
          'mites that prey on spider '
          'mites may be absent or in '
          'low numbers, leading to an '
          'imbalance in the '
          'ecosystem.\n'
          '\n'
          '5. **Weak Plant Vigor:** '
          'Stressed or unhealthy '
          'tomato plants are more '
          'susceptible to spider mite '
          'infestations due to '
          'impaired defenses and '
          'reduced sap production.',
          'Tomato  Target Spot': '1. **Fungal Pathogens:** The primary cause of Tomato '
          'Target Spot is infection by the fungi Alternaria '
          'alternata or Alternaria solani.\n'
          '2. **Environmental Conditions:** Warm, humid '
          'conditions with prolonged leaf wetness favor disease '
          'development.\n'
          '3. **Host Susceptibility:** Certain tomato varieties '
          'are more susceptible to Target Spot, especially those '
          'with thinner leaves and open growth habits.\n'
          '4. **Cultural Practices:** Poor cultural practices, '
          'such as excessive irrigation or dense planting, can '
          'create microclimates conducive to fungal growth.\n'
          '5. **Mechanical Injury:** Wounds on plant tissues '
          'provide entry points for the fungus, increasing the '
          'risk of infection.',
          'Tomato  Yellow Leaf Curl Virus': '**Causes of Tomato Yellow Leaf Curl '
          'Virus:**\n'
          '\n'
          '1. **Viral Infection:** TYLCV is a '
          'begomovirus transmitted by the whitefly '
          'Bemisia tabaci. The virus infects plant '
          'cells and disrupts their growth and '
          'development.\n'
          '\n'
          '2. **Vector Transmission:** Bemisia tabaci '
          'acquires the virus from infected tomato '
          'plants and transmits it to healthy plants '
          'through feeding.\n'
          '\n'
          '3. **Favorable Environmental Conditions:** '
          'TYLCV thrives in warm, dry climates. High '
          'temperatures and low humidity promote '
          'disease development.\n'
          '\n'
          '4. **Virus Mutation:** TYLCV can undergo '
          'mutations, leading to the emergence of new '
          'strains that may be more aggressive or '
          'resistant to existing control measures.\n'
          '\n'
          '5. **Plant Stress:** Stressed tomato '
          'plants, such as those affected by nutrient '
          'deficiency or drought, are more '
          'susceptible to TYLCV infection and may '
          'exhibit severe symptoms.'}
cures = {'Chili  Leaf Curl': '**Cures for Chili Leaf Curl**\n'
         '\n'
         '1. **Early detection and removal:** Remove infected '
         'leaves and destroy them to prevent further spread.\n'
         '\n'
         '2. **Cultural practices:** Use disease-resistant '
         'varieties, rotate crops, and manage weeds to reduce the '
         'spread of the virus.\n'
         '\n'
         '3. **Insecticide control:** Control whiteflies, which '
         'transmit the virus, using insecticides or biological '
         'control agents.\n'
         '\n'
         '4. **Antiviral treatments:** Apply antiviral agents, '
         'such as acibenzolar-S-methyl or thiabendazole, to '
         'infected plants.\n'
         '\n'
         '5. **Genetic engineering:** Develop transgenic chili '
         'plants resistant to the leaf curl virus.',
         'Chili  Leaf Spot': '1. **Cultural Practices:** Promote good air circulation '
         'by spacing plants adequately and pruning excess foliage. '
         'Avoid overhead irrigation, as moisture favors disease '
         'development.\n'
         '2. **Fungicidal Control:** Apply broad-spectrum '
         'fungicides containing copper or chlorothalonil to '
         'prevent or suppress disease outbreaks. Follow label '
         'directions carefully.\n'
         '3. **Resistant Varieties:** Select chili varieties that '
         'have demonstrated resistance to leaf spot, such as '
         "'Early Jalapeño' or 'Big Jim'.\n"
         '4. **Organic Controls:** Use organic fungicides such as '
         'sulfur or neem oil. Apply as directed to combat fungal '
         'pathogens.\n'
         '5. **Proper Pest Management:** Control aphids and other '
         'pests that can transmit leaf spot spores. Use '
         'insecticidal soap or horticultural oil as necessary.',
         'Chili  Whitefly': '**Five Cures for Chili Whitefly:**\n'
         '\n'
         '1. **Biological Control:** Introducing beneficial '
         'insects, such as ladybugs, lacewings, and pirate bugs, to '
         'prey on whiteflies.\n'
         '2. **Chemical Control:** Applying insecticides '
         'specifically designed for whitefly control, such as '
         'imidacloprid or acetamiprid.\n'
         '3. **Cultural Practices:** Using mulches or reflective '
         'covers to deter whiteflies, and promoting plant health '
         'through proper nutrition and watering.\n'
         '4. **Trapping:** Employing yellow sticky traps to attract '
         'and capture adult whiteflies.\n'
         '5. **Resistant Varieties:** Planting chili varieties that '
         'exhibit resistance or tolerance to whitefly infestations.',
         'Chili  Yellowish': '**Cures for Chili Yellowish**\n'
         '\n'
         '1. **Copper Fungicide Application:** Apply a '
         'copper-based fungicide to the soil or foliage to control '
         'fungal infections that often cause yellowing.\n'
         '2. **Iron Supplementation:** Soil or foliar application '
         'of iron chelates can correct iron deficiency, which can '
         'lead to yellowing.\n'
         '3. **pH Adjustment:** Soil pH should be maintained '
         'between 6 and 7 for optimal nutrient uptake by chili '
         'plants. Adjust pH with lime or sulfur as needed.\n'
         '4. **Nutrient Balance:** Ensure adequate levels of '
         'nitrogen, phosphorus, and potassium in the soil. '
         'Balanced fertilization can prevent yellowing due to '
         'nutrient deficiencies.\n'
         '5. **Pest Control:** Inspect chili plants for pests such '
         'as aphids, spider mites, or thrips, which can transmit '
         'viruses or feed on plant tissues, causing yellowing. '
         'Implement appropriate pest control measures.',
         'Corn  Common Rust': '**Cures for Corn Common Rust:**\n'
         '\n'
         '1. **Resistant Varieties:** Plant rust-resistant corn '
         'hybrids or varieties to minimize infection.\n'
         '2. **Fungicides:** Apply foliar fungicides containing '
         'strobilurins or triazoles at the onset of symptoms to '
         'protect healthy leaves.\n'
         '3. **Crop Rotation:** Avoid planting corn in '
         'consecutive years to reduce inoculum buildup in the '
         'soil.\n'
         '4. **Field Sanitation:** Remove and destroy infected '
         'plant debris after harvest to reduce overwintering '
         'spores.\n'
         '5. **Good Cultural Practices:** Proper fertilization, '
         'irrigation, and crop management can promote plant vigor '
         'and resistance to disease.',
         'Corn  Gray Leaf Spot': '**Cures for Corn Gray Leaf Spot**\n'
         '\n'
         '1. **Fungicides:** Apply an appropriate fungicide to '
         "the crop, following the manufacturer's "
         'instructions.\n'
         '2. **Crop Rotation:** Rotate corn crops with '
         'non-host plants, such as soybeans or wheat, to '
         'reduce disease inoculum in the soil.\n'
         '3. **Resistant Varieties:** Plant corn varieties '
         'that have resistance or tolerance to gray leaf '
         'spot.\n'
         '4. **Cultural Practices:** Remove infected plant '
         'debris from the field after harvest, practice proper '
         'irrigation techniques, and provide adequate plant '
         'spacing to promote airflow.\n'
         '5. **Seed Treatment:** Treat corn seeds with a '
         'fungicide before planting to prevent initial '
         'infection.',
         'Corn  Northern Leaf Blight': '**Cures for Corn Northern Leaf Blight**\n'
         '\n'
         '1. **Planting Resistant Varieties:** Select '
         'corn hybrids that exhibit resistance or '
         'tolerance to the Northern Leaf Blight fungus, '
         'such as B73 and D5090.\n'
         '\n'
         '2. **Crop Rotation:** Implement a no-till or '
         'minimum-till crop rotation system to minimize '
         'the buildup of crop residues where the fungus '
         'can overwinter.\n'
         '\n'
         '3. **Foliar Fungicides:** Apply systemic or '
         'protective fungicides to corn fields when '
         'disease symptoms appear or weather conditions '
         'favor infection.\n'
         '\n'
         '4. **Cultural Practices:** Manage leaf canopy '
         'through row spacing and nitrogen fertilization '
         'to promote good airflow and reduce disease '
         'severity.\n'
         '\n'
         '5. **Field Sanitation:** Remove and destroy '
         'infected plant debris after harvest to prevent '
         'disease carryover to the next season.',
         'Mango  Diseased': '1. **Powdery Mildew:** Apply fungicides containing '
         'sulfur, neem oil, or potassium bicarbonate to control '
         'this fungal disease.\n'
         '2. **Anthracnose:** Remove infected fruits and spray with '
         'fungicides such as copper oxychloride or mancozeb.\n'
         '3. **Stem-End Rot:** Manage through sanitation and '
         'fungicide application, ensuring proper storage '
         'conditions.\n'
         '4. **Bacterial Black Spot:** Eradicate infected leaves '
         'and use antibacterial sprays containing copper or '
         'streptomycin.\n'
         '5. **Mango Malformation:** Implement proper pruning '
         'techniques, avoid excessive nitrogen application, and '
         'control vector insects to prevent this physiological '
         'disorder.',
         'Pepper Bell  Bacterial Spot': '**Cures for Pepper Bell Bacterial Spot**\n'
         '\n'
         '1. **Bactericides:** Apply copper-based '
         'bactericides (e.g., Bordeaux mixture, copper '
         'hydroxide) or streptomycin to control the '
         'disease.\n'
         '2. **Cultural Practices:** Remove infected '
         'plants and plant debris to reduce '
         'overwintering pathogen populations. Practice '
         'crop rotation with non-host crops for at '
         'least 3 years.\n'
         '3. **Resistant Varieties:** Plant varieties '
         'resistant to bacterial spot.\n'
         '4. **Sanitation:** Disinfect tools and '
         'equipment used in handling pepper plants. '
         'Avoid overhead irrigation, which promotes '
         'splashing of water and pathogen spread.\n'
         '5. **Seed Treatment:** Treat pepper seeds '
         'with a hot water bath (122°F for 25 minutes) '
         'or sodium hypochlorite (10% bleach solution '
         'for 30 minutes) to kill seed-borne pathogens.',
         'Potato  Early Blight': '**5 Cures for Potato Early Blight:**\n'
         '\n'
         '1. **Fungicides:** Apply a copper-based or mancozeb '
         'fungicide according to label instructions to control '
         'the fungus.\n'
         '\n'
         '2. **Cultural Practices:** Practice crop rotation to '
         'prevent buildup in the soil. Remove infected plants '
         'and debris to reduce inoculum.\n'
         '\n'
         '3. **Resistant Varieties:** Select potato varieties '
         'with resistance to early blight.\n'
         '\n'
         '4. **Fertilization:** Avoid excessive nitrogen '
         'fertilization, which can promote leaf growth and '
         'increase susceptibility.\n'
         '\n'
         '5. **Water Management:** Water plants at the base to '
         'minimize leaf wetness, which favors disease '
         'development.',
         'Potato  Late Blight': '**Cures for Potato Late Blight:**\n'
         '\n'
         '1. **Cultural Practices:** Employ crop rotation, use '
         'disease-free seed, and avoid excessive nitrogen '
         'fertilization to reduce disease pressure.\n'
         '\n'
         '2. **Chemical Control:** Apply fungicides with active '
         'ingredients such as mancozeb, chlorothalonil, or '
         'azoxystrobin when disease conditions are favorable.\n'
         '\n'
         '3. **Resistant Varieties:** Plant varieties with '
         'genetic resistance to Late Blight to minimize disease '
         'severity and reduce yield losses.\n'
         '\n'
         '4. **Biological Control:** Utilize antagonistic '
         'microorganisms, such as Trichoderma or Bacillus '
         'subtilis, as biocontrol agents to suppress disease '
         'development.\n'
         '\n'
         '5. **Early Detection and Removal:** Monitor crops for '
         'early signs of infection and promptly remove and '
         'destroy infected plants to prevent disease spread.',
         'Rice  Brown Spot': '**Cures for Rice Brown Spot**\n'
         '\n'
         '1. **Resistant Varieties:** Select and grow brown '
         'spot-resistant rice cultivars to minimize the risk of '
         'infection.\n'
         '\n'
         '2. **Chemical Control:** Apply fungicides containing '
         'propiconazole, tebuconazole, or tricyclazole at '
         'recommended rates and timings to suppress disease '
         'development.\n'
         '\n'
         '3. **Cultural Practices:** Improve drainage, reduce '
         'plant density, and avoid excessive nitrogen '
         'fertilization to create an environment less favorable '
         'for brown spot development.\n'
         '\n'
         '4. **Crop Rotation:** Rotate rice with non-susceptible '
         'crops to reduce the build-up of the fungus in the soil.\n'
         '\n'
         '5. **Seed Treatment:** Treat rice seeds with fungicides '
         'containing metalaxyl, azoxystrobin, or fluoxastrobin to '
         'protect seedlings from infection.',
         'Rice  Hispa': '**Five Cures for Rice Hispa**\n'
         '\n'
         '1. **Cultural Practices:** Clean field sanitation, crop '
         'rotation, and intercropping with non-host plants can reduce '
         'hispa populations.\n'
         '\n'
         '2. **Biological Control:** Introducing natural enemies such '
         'as ladybugs and parasitic wasps can control hispa '
         'infestations.\n'
         '\n'
         '3. **Chemical Control:** Applying organophosphates, '
         'carbamates, or pyrethroids as foliar sprays can effectively '
         'kill nymphs and adults.\n'
         '\n'
         '4. **Resistant Varieties:** Planting hispa-resistant rice '
         'varieties can significantly reduce crop damage.\n'
         '\n'
         '5. **Integrated Pest Management (IPM):** Combining multiple '
         'methods, including cultural, biological, and chemical '
         'control, in an IPM program provides a comprehensive and '
         'sustainable solution to control Rice Hispa.',
         'Rice  Leaf Blast': '1. **Seed Treatment:** Treating seeds with fungicides '
         '(e.g., propiconazole, tricyclazole) can protect '
         'seedlings from infection.\n'
         '2. **Fungicide Application:** Applying systemic or '
         'contact fungicides (e.g., azoxystrobin, carbendazim) '
         'during the early stages of disease can suppress '
         'infection and reduce disease severity.\n'
         '3. **Resistant Varieties:** Planting resistant or '
         'partially resistant rice cultivars can minimize disease '
         'incidence and severity.\n'
         '4. **Cultural Practices:** Crop rotation, balanced '
         'fertilization, and proper water management can reduce '
         'the build-up of the pathogen and create less favorable '
         'conditions for infection.\n'
         '5. **Integrated Disease Management:** Combining multiple '
         'approaches (e.g., resistant varieties, fungicides, '
         'cultural practices) can provide effective and '
         'sustainable disease control.',
         'Rice  Neck Blast': '1. **Resistant Varieties:** Planting rice varieties '
         'resistant to neck blast, such as those possessing the '
         'Pi-3 gene, can effectively prevent infection and reduce '
         'disease severity.\n'
         '\n'
         '2. **Cultural Practices:** Employing cultural practices '
         'like crop rotation with non-host plants, proper water '
         'management to avoid excessive humidity, and timely '
         'harvesting to minimize disease spread can help control '
         'neck blast.\n'
         '\n'
         '3. **Chemical Control:** Fungicides containing active '
         'ingredients like tricyclazole, benomyl, or propiconazole '
         'can be used to protect rice plants during the vulnerable '
         'tillering and flowering stages.\n'
         '\n'
         '4. **Biological Control:** The use of antagonistic fungi '
         'or bacteria, such as Trichoderma species or Bacillus '
         'subtilis, as biocontrol agents can suppress neck blast '
         'pathogens through competition or antibiosis.\n'
         '\n'
         '5. **Integrated Pest Management (IPM):** A comprehensive '
         'IPM approach that combines multiple methods, including '
         'resistant varieties, cultural practices, chemical '
         'control, and biological control, provides the most '
         'effective and sustainable strategy for managing rice '
         'neck blast disease.',
         'Tomato  Bacterial Spot': '1. **Copper-based bactericides:** Apply copper '
         'fungicides to the soil or foliage, as directed by '
         'the manufacturer. Repeat applications every 7-10 '
         'days throughout the growing season.\n'
         '\n'
         '2. **Antibiotics:** Use antibiotics labeled for '
         'use on tomatoes, such as streptomycin or '
         "oxytetracycline. Follow the manufacturer's "
         'instructions for application rates and timing.\n'
         '\n'
         '3. **Cultural practices:** Rotate crops with '
         'non-host plants; remove infected plant debris; '
         'avoid overhead watering; maintain good drainage.\n'
         '\n'
         '4. **Resistant varieties:** Plant varieties that '
         'have demonstrated resistance to Bacterial Spot, '
         "such as 'Solar Fire' or 'VFNT Cherry.'\n"
         '\n'
         '5. **Seed treatment:** Treat tomato seeds with a '
         'copper-based bactericide before planting to '
         'prevent the introduction of the disease.',
         'Tomato  Early Blight': '**Cures for Tomato Early Blight**\n'
         '\n'
         '1. **Remove Infected Foliage:** Cut away and destroy '
         'affected leaves to prevent spread.\n'
         '2. **Apply Fungicides:** Use copper-based fungicides '
         'or other approved chemicals according to '
         'instructions.\n'
         '3. **Rotate Crops:** Do not plant tomatoes in the '
         'same location for multiple seasons, as the pathogen '
         'can survive in soil.\n'
         '4. **Use Disease-Resistant Varieties:** Choose '
         'cultivars with resistance to early blight.\n'
         '5. **Proper Watering Practices:** Water plants at '
         'the base to avoid wetting foliage and minimize the '
         'spread of spores.',
         'Tomato  Late Blight': '**Five Cures for Tomato Late Blight:**\n'
                        '\n'
                        '1. **Cultural Control:** Remove and destroy infected '
                        'plant material; rotate crops to non-solanaceous '
                        'hosts; keep the foliage dry by avoiding overhead '
                        'watering.\n'
                        '2. **Fungicides:** Apply protectant or systemic '
                        'fungicides, such as chlorothalonil, mancozeb, or '
                        'azoxystrobin, as per label instructions.\n'
                        '3. **Resistant Varieties:** Plant tomato varieties '
                        'with resistance to the late blight pathogen, such as '
                        "'Defiant' or 'Ranger'.\n"
                        '4. **Biological Control:** Use beneficial '
                        'microorganisms, such as Trichoderma spp. or Bacillus '
                        'subtilis, to suppress the pathogen.\n'
                        '5. **Chemical Control:** Apply a commercial copper '
                        'fungicide, such as Bordeaux mixture or copper '
                        'hydroxide, to protect the plants from infection.',
         'Tomato  Leaf Mold': '**Cures for Tomato Leaf Mold:**\n'
         '\n'
         '1. **Fungicides:** Apply fungicides containing '
         'mancozeb, chlorothalonil, or copper sulfate to prevent '
         'and control the spread of leaf mold.\n'
         '2. **Cultural Practices:** Remove infected leaves and '
         'plant debris promptly to reduce the inoculum source. '
         'Practice crop rotation and provide adequate spacing '
         'between plants to improve air circulation.\n'
         '3. **Resistant Varieties:** Choose tomato varieties '
         'that are resistant or tolerant to leaf mold.\n'
         '4. **Greenhouse Management:** In greenhouses, ensure '
         'proper ventilation, reduce humidity levels, and avoid '
         'overwatering to create an environment less conducive to '
         'leaf mold development.\n'
         '5. **Soil Amendment:** Amend the soil with compost or '
         'organic matter to improve soil drainage and suppress '
         'fungal growth.',
         'Tomato  Mosaic Virus': '**Cures for Tomato Mosaic Virus**\n'
         '\n'
         '1. **Prevention:** Inspect plants for symptoms and '
         'remove infected individuals to prevent spread. Use '
         'certified disease-free seeds, sanitize tools, and '
         'maintain good hygiene practices.\n'
         '\n'
         '2. **Cultural Practices:** Allow for proper air '
         'circulation, avoid overwatering, and implement crop '
         'rotation to minimize virus transmission.\n'
         '\n'
         '3. **Chemical Control:** No effective chemical '
         'controls exist, but some products may suppress '
         'symptoms by boosting plant immunity.\n'
         '\n'
         '4. **Biological Control:** Use of natural predators, '
         'such as parasitoid wasps or entomopathogenic fungi, '
         'can help manage virus-carrying insects.\n'
         '\n'
         '5. **Host Resistance:** Plant resistant tomato '
         'varieties, such as Heinz 1350, to minimize the '
         'impact of the virus on crop yield and quality.',
         'Tomato  Septoria Leaf Spot': '1. **Cultural Practices:** Implement crop '
         'rotation, remove diseased plant debris, and '
         'avoid overhead irrigation to reduce inoculum '
         'buildup.\n'
         '2. **Fungicides:** Apply broad-spectrum '
         'fungicides (e.g., chlorothalonil, mancozeb) at '
         'the first sign of symptoms, following label '
         'instructions.\n'
         '3. **Resistant Varieties:** Plant tomato '
         'varieties with resistance to Septoria '
         "lycopersici, such as 'Celebrity,' 'First "
         "Lady,' or 'Mountain Pride.'\n"
         '4. **Foliar Fertilization:** Supplement plants '
         'with foliar fertilizers containing calcium and '
         'potassium to enhance their tolerance to the '
         'disease.\n'
         '5. **Biological Control:** Explore the use of '
         'biocontrol agents, such as Trichoderma '
         'harzianum, to suppress the growth of the '
         'Septoria fungus.',
         'Tomato  Spider Mites (Two Spotted Spider Mite)': '**Five Cures for Tomato '
         'Spider Mites (Two-Spotted '
         'Spider Mite)**\n'
         '\n'
         '1. **Miticides:** Apply a '
         'miticide specifically '
         'labeled for use on '
         'tomatoes, such as '
         'abamectin, bifenazate, or '
         'spiromesifen.\n'
         '\n'
         '2. **Horticultural Oils:** '
         'Spray plants with '
         'horticultural oils, such '
         'as neem oil or rosemary '
         'oil, to smother mites and '
         'repel them.\n'
         '\n'
         '3. **Predatory Mites:** '
         'Release predatory mites '
         '(e.g., Phytoseiulus '
         'persimilis) into the '
         'affected area. These '
         'predators will feed on '
         'spider mites.\n'
         '\n'
         '4. **Insecticidal Soap:** '
         'Prepare a solution of '
         'insecticidal soap (e.g., '
         'potassium soap) and spray '
         'it on plants. This soap '
         'will suffocate mites.\n'
         '\n'
         '5. **Cultural '
         'Practices:**\n'
         '    - Remove infested '
         'leaves and debris.\n'
         '    - Keep plants '
         'well-watered to deter '
         'mites, as they prefer dry '
         'conditions.\n'
         '    - Avoid using nitrogen '
         'fertilizers excessively, '
         'as this can promote lush '
         'growth and attract mites.',
         'Tomato  Target Spot': '1. **Cultural Practices:** Remove infected plant '
                        'debris, practice crop rotation, and avoid excessive '
                        'moisture.\n'
                        '2. **Chemical Control:** Use registered fungicides '
                        'containing pyraclostrobin, trifloxystrobin, or '
                        'chlorothalonil.\n'
                        '3. **Biological Control:** Certain Trichoderma '
                        'species can suppress the disease.\n'
                        '4. **Resistant Varieties:** Plant tomato varieties '
                        "with resistance to Target Spot, such as 'Amelia', "
                        "'Blade', or 'Classic'.\n"
                        '5. **Integrated Disease Management:** Combine '
                        'cultural practices, chemical control, and resistant '
                        'varieties for optimal disease management.',
         'Tomato  Yellow Leaf Curl Virus': '**Cures for Tomato Yellow Leaf Curl Virus '
                                   '(TYLCV)**\n'
                                   '\n'
                                   '1. **Resistant Varieties:** Planting '
                                   'tomato varieties resistant to TYLCV, such '
                                   "as 'Champion', 'Floradade', or 'Natalia', "
                                   'can prevent infection and reduce disease '
                                   'severity.\n'
                                   '\n'
                                   '2. **Vector Control:** Controlling '
                                   'whiteflies, which are the primary vectors '
                                   'of TYLCV, through insecticides, sticky '
                                   'traps, or cultural practices like mulching '
                                   'or companion planting with repellent '
                                   'species, can reduce virus transmission.\n'
                                   '\n'
                                   '3. **Cultural Practices:** Crop rotation, '
                                   'avoiding planting tomatoes in areas with a '
                                   'history of TYLCV, and timely removal of '
                                   'infected plants can help minimize disease '
                                   'spread.\n'
                                   '\n'
                                   '4. **Chemical Control:** Systemic '
                                   'insecticides, such as imidacloprid or '
                                   'acetamiprid, applied as soil drenches or '
                                   'foliar sprays, can kill whiteflies and '
                                   'reduce virus transmission.\n'
                                   '\n'
                                   '5. **Biological Control:** Introducing '
                                   'natural enemies of whiteflies, such as '
                                   'parasitic wasps or lacewings, can help '
                                   'suppress whitefly populations and '
                                   'indirectly reduce TYLCV incidence.'}


def disease_causes(disease):
    # if disease contains 'healthy' then print 'No specific causes and cures'
    # else print the causes of the disease
    if 'healthy' in disease.lower():
        return 'No specific causes since plant is healthy'
    else:
        return causes[disease]


def disease_cures(disease):
    if 'healthy' in disease.lower():
        return 'No specific cures since plant is healthy'
    else:
        return cures[disease]
